export const OPTIONS_CHANGE = "OPTIONS_CHANGE";
export const HOME_TYPE_CHANGE = "HOME_TYPE_CHANGE";
export const REMOVE_VALUE = "REMOVE_VALUE";
export const MOUSEOVER_TOOLTIP_MAP = "MOUSEOVER_TOOLTIP_MAP";
export const FILTER_HOUSES = 'FILTER_HOUSES';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SET_VISIBLE_AREA = 'SET_VISIBLE_AREA';
